import axios from 'axios';
import fs from 'fs';
import path from 'path';
import { config } from '../config/env.js';
import { logger } from '../config/logger.js';

export interface ImageGenerationOptions {
  recipeTitle: string;
  apiName: string;
  referenceImages?: string[];
  albumTitle?: string;
}

export interface ImageResult {
  imageUrl: string;
  localPath: string;
  prompt: string;
}

/**
 * Generate recipe image via configured API
 */
export async function generateRecipeImage(options: ImageGenerationOptions): Promise<ImageResult> {
  const { recipeTitle, apiName, referenceImages } = options;

  // Build optimized food photography prompt
  const prompt = buildImagePrompt(recipeTitle);

  logger.info({ recipeTitle, apiName, hasReferences: !!referenceImages?.length }, 'Generating recipe image');

  try {
    let imageData: string;

    switch (apiName) {
      case 'stability-ai':
        imageData = await generateWithStabilityAI(prompt, referenceImages);
        break;
      
      case 'midjourney':
      case 'replicate':
        // Placeholder - real API integration in future
        imageData = await generatePlaceholderImage(recipeTitle);
        break;
      
      default:
        throw new Error(`Unsupported image API: ${apiName}`);
    }

    // Save image to local storage
    const localPath = await saveImageToLocal(imageData, recipeTitle);

    return {
      imageUrl: localPath,
      localPath,
      prompt,
    };

  } catch (error: any) {
    logger.error({ recipeTitle, error: error.message }, 'Image generation failed');
    throw error;
  }
}

/**
 * Build optimized prompt for food photography
 */
function buildImagePrompt(recipeTitle: string): string {
  return `Professional food photography of ${recipeTitle}, appetizing presentation, high quality, magazine style, natural lighting, vibrant colors, overhead view, rustic wooden table, garnished, bokeh background, 4K, photorealistic`;
}

/**
 * Generate image via Stability AI API
 */
async function generateWithStabilityAI(prompt: string, referenceImages?: string[]): Promise<string> {
  if (!config.sdxlApiKey) {
    throw new Error('SDXL_API_KEY is not configured');
  }

  const requestBody: any = {
    text_prompts: [
      {
        text: prompt,
        weight: 1,
      },
      {
        text: 'blurry, low quality, distorted, unappetizing, raw meat, burnt food',
        weight: -1,
      },
    ],
    cfg_scale: 7,
    height: 1024,
    width: 1024,
    steps: 30,
    samples: 1,
  };

  // Add reference image if provided (init_image for img2img)
  if (referenceImages && referenceImages.length > 0) {
    // For Stability AI, we'd need to download the reference image
    // and convert it to base64, then use init_image parameter
    // Simplified for MVP - just use text2img for now
    logger.info({ hasReference: true }, 'Reference image provided but using text2img for MVP');
  }

  try {
    const response = await axios.post(
      config.sdxlApiUrl || 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
      requestBody,
      {
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'Authorization': `Bearer ${config.sdxlApiKey}`,
        },
        timeout: 60000, // 60 seconds
      }
    );

    const artifacts = response.data.artifacts;
    if (!artifacts || artifacts.length === 0) {
      throw new Error('No image generated by Stability AI');
    }

    return artifacts[0].base64;

  } catch (error: any) {
    logger.error({ error: error.message }, 'Stability AI request failed');
    throw new Error(`Stability AI failed: ${error.message}`);
  }
}

/**
 * Generate placeholder image for unsupported APIs
 */
async function generatePlaceholderImage(recipeTitle: string): Promise<string> {
  // Return a data URL for a simple placeholder
  // In production, this would call actual APIs
  const placeholder = Buffer.from('placeholder-image-data').toString('base64');
  return placeholder;
}

/**
 * Save base64 image to local filesystem
 */
async function saveImageToLocal(base64Data: string, recipeTitle: string): Promise<string> {
  // Create images directory if it doesn't exist
  const imagesDir = path.join(process.cwd(), 'storage', 'images');
  if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
  }

  // Generate unique filename
  const timestamp = Date.now();
  const slug = slugify(recipeTitle);
  const fileName = `${timestamp}-${slug}.jpg`;
  const filePath = path.join(imagesDir, fileName);

  // Convert base64 to buffer and save
  const imageBuffer = Buffer.from(base64Data, 'base64');
  fs.writeFileSync(filePath, imageBuffer);

  logger.info({ filePath, recipeTitle }, 'Image saved to local storage');

  // Return relative path (for serving via static middleware in future)
  return `/storage/images/${fileName}`;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 50);
}
